# Conda Environment Setup Instructions
#  - Using an environment.yml file with conda
#  - Key Terminal Commands:
#
#    conda env create -f environment.yml
#    conda env update --file environment.yml --prune
#    conda env export --name tracking-barbell-exercises > environment.yml
#    conda env remove --name tracking-barbell-exercises
#    conda env list

name: ml-barbel-workout-tracking
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.12.1
  - pip
  - bottleneck
  - pip:
      - numpy==1.26.4
      - pandas==2.2.2
      - ipykernel==6.28.0
      - ipython==8.25.0
      - jupyter-client==7.4.7
      - jupyter-core==5.1.0
      - matplotlib==3.8.4
      - notebook==7.0.8
      - packaging
